name: Demo Github Actions workflows
on:
  workflow_dispatch:
  push:
    branches: [develop]
    
jobs:
  demo: 
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
