name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      name: 
        description: 'this is a test variable'
        type: string
        default: 'test'
    
jobs:
  demo: 
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "${{ inputs.name }}"
