name: Manual Workflow with Number Input

on:
  workflow_dispatch:
    inputs:
      deployment_version:
        description: 'Specify the deployment version number'
        required: true
        type: number
        default: "1.0"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Deployment Version
        run: |
          echo "Deploying version: ${{ github.event.inputs.deployment_version }}"
