name: Manual Workflow with all workflow dispatch inputs

on:
  workflow_dispatch:
    inputs:
      deployment_version:
        description: 'Specify the deployment version number'
        required: true
        type: number
        default: "1.0"
      environment:
        description: 'select environment'
        type: choice
        options:
          - dev
          - stage
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Deployment Version
        run: |
          echo "Deploying version: ${{ github.event.inputs.deployment_version }}"
          echo "Deploying on Environment: ${{ github.event.inputs.environment }}"
